version: '3.8'

services:
  # ==============================
  # LAYER 2: 🧠 Backend API
  # ==============================
  backend_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: house_prediction_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # 🔥 THIS IS NEW: It gives the API access to your saved .joblib models!
      - ./artifacts:/app/artifacts  

  # ==============================
  # LAYER 3: 💻 Web Frontend (Nginx)
  # ==============================
  frontend_web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: house_prediction_web
    ports:
      - "9090:80"
    depends_on:
      - backend_api



  # ==============================
  # LAYER 4: ⚙️ Training Engine
  # ==============================
  training_engine:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: house_prediction_trainer
    profiles:
      - training  # 🔥 This prevents it from running automatically!
    env_file:
      - .env
    volumes:
      # It needs the artifacts folder to save the .joblib files so the API can read them!
      - ./artifacts:/app/artifacts 
    # Override the API's Gunicorn command to run our Master Trigger instead
    command: ["python", "-m", "backend.main"]