version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    environment:
      - DAGSHUB_USERNAME=${DAGSHUB_USERNAME}
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
    networks:
      - enterprise_ml_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - enterprise_ml_net

networks:
  enterprise_ml_net:
    driver: bridge